server:
  port: 80

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@54.180.8.49:1521/XE
    username: lgs0503
    password: 0609

mybatis:
  mapper-locations: classpath:mapper/**.xml
